[package]
name = "testpath"
version = "0.0.0"
edition = "2018"
description = "companinon crate to bintest/testcall, augments Paths for testing"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cehteh/testpath.git"
keywords = ["testing"]

[dependencies]
